name: Build Android APK

on:
  push:
    branches:
      - main

    paths:

      - 'android-template/**'

      - '.github/workflows/android.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Permission
        run: chmod +x gradlew
        working-directory: android-template/WebAppEngine

      - name: Clean Gradle
        run: ./gradlew clean
        working-directory: android-template/WebAppEngine

      - name: Remove Default WebP Icons
        run: |

          rm -f app/src/main/res/mipmap-mdpi/ic_launcher.webp
          rm -f app/src/main/res/mipmap-hdpi/ic_launcher.webp
          rm -f app/src/main/res/mipmap-xhdpi/ic_launcher.webp
          rm -f app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
          rm -f app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp

          rm -f app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
          rm -f app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
          rm -f app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
          rm -f app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
          rm -f app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp

        working-directory: android-template/WebAppEngine



      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: android-template/WebAppEngine

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: generated-apk
          path: android-template/WebAppEngine/app/build/outputs/apk/debug/app-debug.apk