name: Build Android APK

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Dependencies
        run: npm install

  
      - name: Remove Old Icons
        run: |

          find android-template/WebAppEngine/app/src/main/res -name "*.webp" -delete

          find android-template/WebAppEngine/app/src/main/res -name "ic_launcher.webp" -delete

          find android-template/WebAppEngine/app/src/main/res -name "ic_launcher_round.webp" -delete

      - name: Force Clean Build
        run: |

          cd android-template/WebAppEngine

          chmod +x gradlew

          ./gradlew clean

      - name: Build APK
        run: |

          cd android-template/WebAppEngine

          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-apk
          path: |

            android-template/WebAppEngine/app/build/outputs/apk/debug/*.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:

          tag_name: release-${{ github.run_id }}

          files: |

            android-template/WebAppEngine/app/build/outputs/apk/debug/*.apk